version: '2'

volumes:
  mysql_data:
    driver: local

services:
  mysql:
    image: mysql:5.7
    volumes:
    - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jbpm
      MYSQL_USER: jbpm
      MYSQL_PASSWORD: jbpm
  jbpm:
    image: jboss/business-central-workbench-showcase
    environment:
      JBPM_DB_DRIVER: mysql
      JBPM_DB_HOST: mysql
    ports:
      - 8080:8080
      - 8001:8001
    depends_on:
      - mysql
  kie-server:
    image: jboss/kie-server-showcase
    environment:
      KIE_SERVER_LOCATION: http://kie-server:8080/kie-server/services/rest/server
      KIE_SERVER_CONTROLLER: http://jbpm:8080/business-central/rest/controller
      KIE_MAVEN_REPO: http://jbpm:8080/business-central/maven2
    ports:
      - 8180:8080
    depends_on:
      - jbpm